name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 01_setup
        run: ./01_setup.sh
      - name: 02_build
        run: ./02_build.sh
      - name: 04_package.sh
        run: ./04_package.sh
      - uses: actions/upload-artifact@v2
        with:
          name: inotifywait.tar.gz
          path: release/inotifywait.tar.gz
